name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VCPKG_COMMITTISH: dd3097e305afa53f7b4312371f62058d2e665320  # 2025.07.25

jobs:
  check-formatting-and-spelling:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up tools
        run: |
          sudo apt update -q
          sudo apt install -y clang-format-19
          pipx install cmakelang codespell
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-19 9999

      - name: Print versions
        run: |
          python --version
          pipx --version
          cmake --version
          clang-format --version
          clang-format-19 --version
          cmake-format --version
          codespell --version

      - name: Check code formatting
        run: cmake -P CMake/Format.cmake

      - name: Check spelling
        run: cmake -P CMake/Spell.cmake

  build-and-test:
    needs: check-formatting-and-spelling
    strategy:
      fail-fast: false
      matrix:
        # Keeping only the `include:` part below would be sufficient to generate the same matrix
        # combinations, but then the job names would contain all the variables, making them very
        # long. Having just the compiler is much nicer.
        compiler:
          - MSVC
          - clang-cl
          - GCC
          - Clang
        # TODO: Try windows-2025
        include:
          - compiler: MSVC
            preset: ci-windows-msvc
            compiler-pascal-case: Msvc
            os: windows-2022
          - compiler: clang-cl
            preset: ci-windows-clang-cl
            compiler-pascal-case: ClangCl
            os: windows-2022
          - compiler: GCC
            compiler-setup-cpp: gcc-14
            preset: "ci-ubuntu"
            compiler-pascal-case: Gcc
            os: ubuntu-24.04
          - compiler: Clang
            compiler-setup-cpp: llvm-19
            preset: "ci-ubuntu"
            compiler-pascal-case: Clang
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC environment
        if: ${{ matrix.compiler == 'clang-cl' }}
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true

      - name: Set up C++ compiler and tools
        if: ${{ runner.os == 'Linux' }}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler-setup-cpp }}
          clang-tidy: 19
          cppcheck: true
          gcovr: true

      - name: Install valgrind
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update -q
          sudo apt install -y valgrind

      - name: Print versions
        shell: bash
        run: |
          cl || true
          clang-cl --version || true
          g++ --version || true
          clang++ --version || true
          cmake --version || true
          ninja --version || true
          clang-tidy --version || true
          cppcheck --version || true
          gcovr --version || true
          gcov --version || true
          llvm-cov --version || true
          valgrind --version || true

      - name: Set up vcpkg
        uses: fantana21/set-up-vcpkg@v1
        with:
          committish: ${{ env.VCPKG_COMMITTISH }}
          cache-key: vcpkg-${{ matrix.os }}-${{ matrix.compiler }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}-${{ github.sha }}
          cache-restore-keys: |
            vcpkg-${{ matrix.os }}-${{ matrix.compiler }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}
            vcpkg-${{ matrix.os }}-${{ matrix.compiler }}
            vcpkg-${{ matrix.os }}
          save-always: true
          use-private-registry: true
          private-registry-pat: ${{ secrets.VCPKG_REGISTRY_PAT }}

      - name: Pre-seed credentials for private repos
        if: ${{ runner.os == 'Windows' }}
        run: |
          "url=https://github.com`nusername=AllRepositories`npassword=${{ secrets.ALL_REPOSITORIES_PAT }}`n" | git credential approve

      - name: Set up credential helper for private repos
        if: ${{ runner.os == 'Linux' }}
        run: |
          git config --global credential.https://github.com/fantana21.helper '!f() { echo username=AllRepositories; echo password=${{ secrets.ALL_REPOSITORIES_PAT }}; }; f'

      - name: Improve parallelism of MSBuild
        if: ${{ matrix.compiler == 'MSVC' }}
        run: |
          Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
          Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

      - name: Build and test debug and release mode
        shell: bash
        id: test
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}-debug | tee ${{ matrix.compiler }}_Debug_build.log
          ctest --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}-release | tee ${{ matrix.compiler }}_Release_build.log
          ctest --preset ${{ matrix.preset }}

      - name: Build, test, and generate coverage reports
        if: ${{ runner.os == 'Linux' }}
        id: coverage
        run: cmake --workflow --preset ci-coverage

      - name: Build and test with sanitizers
        if: ${{ runner.os == 'Linux' && !cancelled() && steps.test.conclusion == 'success' }}
        id: sanitize
        run: cmake --workflow --preset ci-sanitize

      - name: Build and test debug and release mode with Valgrind
        # Running tests with Valgrind is slow, so we only do it if running them with sanitizers
        # succeeded
        if: ${{ runner.os == 'Linux' && !cancelled() && steps.sanitize.conclusion == 'success' }}
        run: cmake --workflow --preset ci-valgrind

      - name: Report coverage results as artifact and PR comment
        if: ${{ runner.os == 'Linux' && !cancelled() && steps.coverage.conclusion == 'success' }}
        uses: fantana21/report-coverage@v1
        with:
          add-job-summary: false
          artifact-name: CoverageReport${{ matrix.compiler-pascal-case }}
          pr-comment-header: ${{ matrix.compiler }} coverage report

      - name: Count and report warnings as job summary and PR comment
        if: ${{ !cancelled() && steps.test.conclusion == 'success' }}
        uses: fantana21/report-warnings@v1
        with:
          build-logs: |
            ${{ matrix.compiler }}_Debug_build.log
            ${{ matrix.compiler }}_Release_build.log
          pr-comment-header: ${{ matrix.compiler }} warnings report
