name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VCPKG_COMMITTISH: 49ac2134b31b95b0ddf29d56873dcd24392691df

jobs:
  check-formatting-and-spelling:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up tools
        run: |
          sudo apt update -q
          sudo apt install -y clang-format-19
          pipx install cmakelang codespell
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-19 9999

      - name: Print versions
        run: |
          python --version
          pipx --version
          cmake --version
          clang-format --version
          clang-format-19 --version
          cmake-format --version
          codespell --version

      - name: Check code formatting
        run: cmake -P CMake/Format.cmake

      - name: Check spelling
        run: cmake -P CMake/Spell.cmake

  test-windows:
    needs: check-formatting-and-spelling
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true

      - name: Print versions
        run: |
          cmake --version
          ninja --version
          cl --version || true
          clang-cl --version || true

        # TODO: Think about removing VCPKG_COMMITTISH from the cache key
      - name: Set up vcpkg
        uses: fantana21/set-up-vcpkg@v1
        with:
          committish: ${{ env.VCPKG_COMMITTISH }}
          cache-key: vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}-${{ github.sha }}
          cache-restore-keys: |
            vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}
            vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}
            vcpkg-${{ runner.os }}
          save-always: true
          use-private-registry: true
          private-registry-pat: ${{ secrets.VCPKG_REGISTRY_PAT }}

      - name: Pre-seed credentials for private repos
        run: |
          "url=https://github.com`nusername=AllRepositories`npassword=${{ secrets.ALL_REPOSITORIES_PAT }}`n" | git credential approve

      - name: Improve parallelism of MSBuild
        run: |
          Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
          Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

      - name: Build and test debug and release mode (MSVC)
        run: |
          cmake --preset ci-windows-msvc
          cmake --build --preset ci-windows-msvc-debug | Tee-Object -FilePath MSVC_Debug_build.log
          ctest --preset ci-windows-msvc
          cmake --build --preset ci-windows-msvc-release | Tee-Object -FilePath MSVC_Release_build.log
          ctest --preset ci-windows-msvc

      - name: Build and test debug and release mode (clang-cl)
        run: |
          cmake --preset ci-windows-clang-cl
          cmake --build --preset ci-windows-clang-cl-debug | Tee-Object -FilePath Clang-cl_Debug_build.log
          ctest --preset ci-windows-clang-cl
          cmake --build --preset ci-windows-clang-cl-release | Tee-Object -FilePath Clang-cl_Release_build.log
          ctest --preset ci-windows-clang-cl

      - name: Count and report warnings
        uses: fantana21/report-warnings@v1
        with:
          build-logs: |
            MSVC_Debug_build.log
            MSVC_Release_build.log
            Clang-cl_Debug_build.log
            Clang-cl_Release_build.log
          artifact-name: WarningsReportWindows
          pr-comment-header: windows warnings report

  test-ubuntu:
    needs: check-formatting-and-spelling
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up tools
        run: |
          sudo apt update -q
          sudo apt install -y gcc-14 g++-14
          sudo apt install -y clang-19 clang-tidy-19 llvm-19
          sudo apt install -y cppcheck valgrind
          pipx install gcovr
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 9999
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 9999
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-14 9999
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 9999
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 9999
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-19 9999
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-19 9999

      - name: Print and store versions
        shell: pwsh
        run: |
          g++ --version
          clang++ --version
          cmake --version
          ninja --version
          clang-tidy --version
          cppcheck --version
          gcovr --version
          gcov --version
          llvm-cov --version
          valgrind --version

          $CLANG_VERSIONS = (clang++ --version | Select-String -Pattern '([0-9]+)\.([0-9]+)\.([0-9]+)').Matches.Groups.Value
          "CLANG_MAJOR_VERSION=$($CLANG_VERSIONS[1])" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set up vcpkg
        id: set-up-vcpkg
        uses: fantana21/set-up-vcpkg@v1
        with:
          committish: ${{ env.VCPKG_COMMITTISH }}
          cache-key: vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}-${{ github.sha }}
          cache-restore-keys: |
            vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}
            vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMITTISH }}
            vcpkg-${{ runner.os }}
          save-always: true
          use-private-registry: true
          private-registry-pat: ${{ secrets.VCPKG_REGISTRY_PAT }}

      - name: Set up credential helper for private repos
        run: |
          git config --global credential.https://github.com/fantana21.helper '!f() { echo username=QuantNd; echo password=${{ secrets.ALL_REPOSITORIES_PAT }}; }; f'

      - name: Build and test debug and release mode (GCC)
        id: test-gcc
        run: |
          export CXX=g++
          cmake --preset ci-ubuntu
          cmake --build --preset ci-ubuntu-debug | tee GCC_Debug_build.log
          ctest --preset ci-ubuntu
          cmake --build --preset ci-ubuntu-release | tee GCC_Release_build.log
          ctest --preset ci-ubuntu

      - name: Build, test, and generate coverage reports (GCC)
        id: coverage-gcc
        run: |
          export CXX=g++
          cmake --workflow --preset ci-coverage

      - name: Build and test with sanitizers (GCC)
        id: sanitize-gcc
        if: ${{ !cancelled() && steps.test-gcc.conclusion == 'success' }}
        run: |
          export CXX=g++
          cmake --workflow --preset ci-sanitize

      - name: Build and test debug and release mode with Valgrind (GCC)
        # Running tests with Valgrind is slow, so we only do it if running them with sanitizers
        # succeeded
        id: valgrind-gcc
        if: ${{ !cancelled() && steps.sanitize-gcc.conclusion == 'success' }}
        run: |
          export CXX=g++
          cmake --workflow --preset ci-valgrind

      - name: Build and test debug and release mode (Clang)
        id: test-clang
        if: ${{ !cancelled() && steps.set-up-vcpkg.conclusion == 'success' }}
        run: |
          rm -rf build
          export CXX=clang++
          cmake --preset ci-ubuntu
          cmake --build --preset ci-ubuntu-debug | tee Clang_Debug_build.log
          ctest --preset ci-ubuntu
          cmake --build --preset ci-ubuntu-release | tee Clang_Release_build.log
          ctest --preset ci-ubuntu

      - name: Build, test, and generate coverage reports (Clang)
        id: coverage-clang
        if: ${{ !cancelled() && steps.test-clang.conclusion == 'success' }}
        run: |
          export CXX=clang++
          cmake --workflow --preset ci-coverage

      - name: Build and test with sanitizers (Clang)
        id: sanitize-clang
        if: ${{ !cancelled() && steps.test-clang.conclusion == 'success' }}
        run: |
          export CXX=clang++
          cmake --workflow --preset ci-sanitize

      - name: Build and test debug and release mode with Valgrind (Clang)
        # Running tests with Valgrind is slow, so we only do it if running them with sanitizers
        # succeeded.
        if: ${{ !cancelled() && steps.sanitize-clang.conclusion == 'success' }}
        run: |
          export CXX=clang++
          cmake --workflow --preset ci-valgrind

      - name: Count and report warnings
        if: ${{ !cancelled() && steps.test-gcc.conclusion == 'success' && steps.test-clang.conclusion == 'success' }}
        uses: fantana21/report-warnings@v1
        with:
          build-logs: |
            GCC_Debug_build.log
            GCC_Release_build.log
            Clang_Debug_build.log
            Clang_Release_build.log
          artifact-name: WarningsReportUbuntu
          pr-comment-header: ubuntu warnings report

      - name: Report coverage results as job summary, PR comment, and artifact (GCC)
        if: ${{ !cancelled() && steps.coverage-gcc.conclusion == 'success' }}
        uses: fantana21/report-coverage@v1
        with:
          pr-comment-header: gcc
          artifact-name: CoverageReportsGcc

      - name: Report coverage results as job summary, PR comment, and artifact (Clang)
        if: ${{ !cancelled() && steps.coverage-clang.conclusion == 'success' }}
        uses: fantana21/report-coverage@v1
        with:
          pr-comment-header: clang
          artifact-name: CoverageReportsClang
